create_table_query = """
    CREATE TABLE IF NOT EXISTS nike (
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id VARCHAR(100),
    pid VARCHAR(20),
    product_id VARCHAR(100),
    product_instance_id VARCHAR(100),
    product_type VARCHAR(40),
    title VARCHAR(255),
    subtitle VARCHAR(255),
    color_description VARCHAR(255),
    currency VARCHAR(20),
    current_price NUMERIC(12, 3),
    discounted VARCHAR(5),
    employee_price NUMERIC(12, 3),
    full_price NUMERIC(12, 3),
    minimum_advertised_price NUMERIC(12, 3),
    label VARCHAR(40),
    in_stock VARCHAR(5),
    is_coming_soon VARCHAR(5),
    is_best_seller VARCHAR(5),
    is_excluded VARCHAR(5),
    is_gift_card VARCHAR(5),
    is_jersey VARCHAR(5),
    is_launch VARCHAR(5),
    is_member_exclusive VARCHAR(5),
    is_nba VARCHAR(5),
    is_nfl VARCHAR(5),
    is_sustainable VARCHAR(5),
    has_extended_sizing VARCHAR(5),
    customizable VARCHAR(5),
    search_term VARCHAR(40),
    portrait_url VARCHAR(255),
    squarish_url VARCHAR(255),
    url VARCHAR(255)
    )
    """

insert_data_query = """
    INSERT INTO nike (
        id,
        pid,
        product_id,
        product_instance_id,
        product_type,
        title,
        subtitle,
        color_description,
        currency,
        current_price,
        discounted,
        employee_price,
        full_price,
        minimum_advertised_price,
        label,
        in_stock,
        is_coming_soon,
        is_best_seller,
        is_excluded,
        is_gift_card,
        is_jersey,
        is_launch,
        is_member_exclusive,
        is_nba,
        is_nfl,
        is_sustainable,
        has_extended_sizing,
        customizable,
        search_term,
        portrait_url,
        squarish_url,
        url
        )
    VALUES (
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s
    )
    """

