create_table_query = """
    CREATE TABLE IF NOT EXISTS stockx (
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    uuid VARCHAR(50),
    shoe VARCHAR(150),
    title VARCHAR(150),
    brand VARCHAR(20),
    colorway VARCHAR(50),
    condition VARCHAR(20),
    description VARCHAR(255),
    product_category VARCHAR(50),
    release_date VARCHAR(20),
    retail_price NUMERIC(10, 2),
    lowest_ask NUMERIC(10, 2),
    sales_this_period INTEGER,
    sales_last_period INTEGER,
    highest_bid NUMERIC(10, 2),
    volatility NUMERIC(6, 5),
    deadstock_sold INTEGER,
    price_premium NUMERIC(5, 4),
    average_deadstock_price INTEGER,
    last_sale INTEGER,
    change_value INTEGER,
    change_percentage NUMERIC(8, 7),
    last_lowest_ask_time INTEGER,
    last_highest_bid_time INTEGER,
    last_sale_date VARCHAR(40),
    url_key VARCHAR(75),
    small_image_url VARCHAR(255),
    thumb_url VARCHAR(255),
    )
    """

insert_data_query = """
    INSERT INTO stockx (
        id,
        uuid,
        shoe,
        title,
        brand,
        colorway,
        condition,
        description,
        product_category,
        release_date,
        retail_price,
        lowest_ask,
        sales_this_period,
        sales_last_period,
        highest_bid,
        volatility,
        deadstock_sold,
        price_premium,
        average_deadstock_price,
        last_sale,
        change_value,
        change_percentage,
        last_lowest_ask_time,
        last_highest_bid_time,
        last_sale_date,
        url_key,
        small_image_url,
        thumb_url,
        )
    VALUES (
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s
    )
    """
